### PR TITLE
Update `https-proxy-agent` to fix a vulnerability

### PR DESCRIPTION
**Pull request by adrukh**
See https://github.com/TooTallNate/node-https-proxy-agent/pull/77

~I took the liberty to bump the version to `3.1.0`, let me know if you want to do this on a separate commit.~

### CODE REVIEW

**Comment by TooTallNate** [comment]
The version bump should indeed be a separate commit. Can you remove that part please?

**Comment by adrukh** [comment]
Done!

**Comment by adrukh** [comment]
Kind ask to publish this as a non-breaking change 🙏 Unless you think it is?

**Comment by lili2311** [comment]
👋 @TooTallNate please let me know if there is anything else before this can be merged and released? Would lobe to get the two referenced Snyk issues fixed.

**Pull request merged**
